Added database setup and first endpoint to add and edit users
jaqubm/calorieCounter_backend pull request #7
Opened 2024-10-11 13:11 UTC by PiotrJurek

DB Schema:
![DB Schema)](https://github.com/user-attachments/assets/d58b87c4-1d54-4d79-89e9-5569d2def9d0)

Closes #4 and #5.

2024-10-11 13:48 UTC, jaqubm requested changes

2024-10-11 13:48 UTC, jaqubm commented on Controllers/UserController.cs
> +public class UserController(IUserRepository _userRepository) : ControllerBase
Dlaczego _user... tak nazywamy zmienne tylko w przypadku deklarowania ich poniżej w sposób private readonly... W tym wypadku podłoga jest zbędna i myląca

2024-10-11 13:48 UTC, jaqubm commented on Controllers/UserController.cs
> +    [HttpPost("add")]
Trzymaj się zasad C# - "Add" zamiast "add"

2024-10-11 13:48 UTC, jaqubm commented on Controllers/UserController.cs
> +    [HttpPut("update/{id}")]
To samo jak wyżej

2024-10-11 13:48 UTC, jaqubm commented on DB.sql
> +CREATE DATABASE DotNetCourseDatabase;
Po co? Baza jest stworzona, w tym pliku masz do niej tylko zrobić schema i dodać tabelki, usuń te linijki tworzące bazę!

2024-10-11 13:48 UTC, jaqubm commented on Data/DataContext.cs
> +        optionsBuilder.UseSqlServer(config.GetConnectionString("TestSQL"),
Dlaczego?

2024-10-11 13:48 UTC, jaqubm commented on appsettings.json
> +    "TestSQL": "Server=localhost;Database=DotNetCourseDatabase;Trusted_Connection=false;TrustServerCertificate=True;User Id=sa;Password=SQLConnect1!;"
Nawet devowego ConnectionStringa nie powinieneś przesyłać, stworzyłem "AzureSQL": "KEY" po to żebyś mógł sobie lokalnie podstawić tam klucz połączenia i go nie pushować, a pipeline będzie tam wklejał klucz połączenia dynamicznie z sekretu

2024-10-11 16:57 UTC, jaqubm requested changes

2024-10-11 16:57 UTC, jaqubm commented on Controllers/UserController.cs
> +    public IActionResult AddUser([FromBody] User newUser)
Aaa i jeszcze jedno, totalnie nie tak chcemy zrobić ten endpoint, bardziej coś takiego:

```
[HttpPost("SignIn")]
    public async Task<IActionResult> SignIn([FromBody] string accessToken)
    {
        if (string.IsNullOrEmpty(accessToken))
            return Unauthorized("Access token is required.");

        try
        {
            var user = await AuthHelper.GetUserFromGoogleToken(accessToken);
            
            if (userRepository.UserAlreadyExist(user.Email)) return Ok();
        
            userRepository.AddEntity(user);
            
            return userRepository.SaveChanges() ? Ok() : Unauthorized("Failed to add user to database.");
        }
        catch (Exception e)
        {
            return Unauthorized(e.Message);
        }
    }
```
    
    Po to właśnie tą funkcję tworzyłem, żeby nie przekazywać takich danych, tylko token i my z tokena te dane rozszyfrujemy sobie

2024-10-14 14:31 UTC, PiotrJurek commented
New DB Schema:
![DB Schema)](https://github.com/user-attachments/assets/b1c3ec4e-ce07-40a0-9dd2-8e83b1a20c79)

2024-10-14 14:43 UTC, jaqubm requested changes

2024-10-14 14:43 UTC, jaqubm commented on DB.sql
> +CREATE TABLE calorieCounter.[Products] (
Użyj konwencji nazewniczej C# / .NET - Id zamiast id, Name zamiast name

2024-10-14 16:46 UTC, PiotrJurek commented
![FINAL FINAL VERSION](https://github.com/user-attachments/assets/34c1d007-7e4f-4abd-9a8c-a2938e3144f9)

2024-10-14 16:47 UTC, jaqubm approved these changes

2024-10-14 16:47 UTC, merged